// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project1.DatabaseContext;

#nullable disable

namespace Project1.Migrations
{
    [DbContext(typeof(ReactContext))]
    [Migration("20230221162010_migrations")]
    partial class migrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Project1.Models.CreateAcc", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("confirmPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("CreateAcc");
                });

            modelBuilder.Entity("Project1.Models.ListProduct", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("createdAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("ListProducts");

                    b.HasData(
                        new
                        {
                            id = 1,
                            category = "shirts",
                            color = "black,gray",
                            createdAt = "2020",
                            img = "https://d3o2e4jr3mxnm3.cloudfront.net/Mens-Jake-Guitar-Vintage-Crusher-Tee_68382_1_lg.png",
                            price = "600",
                            size = "L,XL",
                            title = "Leather-Coat"
                        },
                        new
                        {
                            id = 2,
                            category = "shirts",
                            color = "yellow",
                            createdAt = "2022",
                            img = "https://www.pngarts.com/files/3/Red-Dress-PNG-Transparent-Image.png",
                            price = "800",
                            size = "S,M,L,XL,XXL",
                            title = "Fur-Coat"
                        },
                        new
                        {
                            id = 3,
                            category = "shirts",
                            color = "darkgray,gray",
                            createdAt = "2017",
                            img = "https://www.prada.com/content/dam/pradanux_products/U/UCS/UCS319/1YOTF010O/UCS319_1YOT_F010O_S_182_SLF.png",
                            price = "400",
                            size = "M,L,XL",
                            title = "Outerwear"
                        },
                        new
                        {
                            id = 4,
                            category = "shirts",
                            color = "red,black",
                            createdAt = "2015",
                            img = "https://www.burdastyle.com/pub/media/catalog/product/cache/7bd3727382ce0a860b68816435d76e26/107/BUS-PAT-BURTE-1320516/1170x1470_BS_2016_05_132_front.png",
                            price = "500",
                            size = "L,XL",
                            title = "Sweaters"
                        },
                        new
                        {
                            id = 5,
                            category = "accessory",
                            color = "black,blue",
                            createdAt = "2019",
                            img = "https://images.ctfassets.net/5gvckmvm9289/3BlDoZxSSjqAvv1jBJP7TH/65f9a95484117730ace42abf64e89572/Noissue-x-Creatsy-Tote-Bag-Mockup-Bundle-_4_-2.png",
                            price = "100",
                            size = "S,M",
                            title = "Mens-Black-Beanie"
                        },
                        new
                        {
                            id = 6,
                            category = "accessory",
                            color = "black,darkblue",
                            createdAt = "2021",
                            img = "https://d3o2e4jr3mxnm3.cloudfront.net/Rocket-Vintage-Chill-Cap_66374_1_lg.png",
                            price = "250",
                            size = "L,XL",
                            title = "Plaid-Skirt"
                        },
                        new
                        {
                            id = 7,
                            category = "accessory",
                            color = "blue",
                            createdAt = "2012",
                            img = "https://www.pngarts.com/files/5/Black-Jacket-Transparent-Background-PNG.png",
                            price = "280",
                            size = "M,L,XL",
                            title = "Sequin-Skirt"
                        },
                        new
                        {
                            id = 8,
                            category = "shirts",
                            color = "gray, black",
                            createdAt = "2011",
                            img = "https://www.pngarts.com/files/3/Women-Jacket-PNG-High-Quality-Image.png",
                            price = "550",
                            size = "L,XL",
                            title = "Women-Jacket"
                        },
                        new
                        {
                            id = 9,
                            category = "Trousers",
                            color = "gray,black",
                            createdAt = "2011",
                            img = "https://www.pngarts.com/files/3/Women-Jacket-PNG-High-Quality-Image.png",
                            price = "325",
                            size = "L,XL,XXL",
                            title = "Women-Jacket"
                        });
                });

            modelBuilder.Entity("Project1.Models.Login", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Login");
                });

            modelBuilder.Entity("Project1.Models.ProductPopular", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("createdAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("ProductPopular");

                    b.HasData(
                        new
                        {
                            id = 1,
                            color = "white",
                            createdAt = "2020",
                            img = "../../wwwroot/img/Screenshot (1).png",
                            size = "M",
                            title = "Leather-Coat"
                        },
                        new
                        {
                            id = 2,
                            color = "red",
                            createdAt = "2022",
                            img = "https://www.pngarts.com/files/3/Red-Dress-PNG-Transparent-Image.png",
                            size = "L",
                            title = "Fur-Coat"
                        },
                        new
                        {
                            id = 3,
                            color = "white",
                            createdAt = "2017",
                            img = "https://www.prada.com/content/dam/pradanux_products/U/UCS/UCS319/1YOTF010O/UCS319_1YOT_F010O_S_182_SLF.png",
                            size = "M",
                            title = "Outerwear"
                        },
                        new
                        {
                            id = 4,
                            color = "black",
                            createdAt = "2015",
                            img = "https://www.burdastyle.com/pub/media/catalog/product/cache/7bd3727382ce0a860b68816435d76e26/107/BUS-PAT-BURTE-1320516/1170x1470_BS_2016_05_132_front.png",
                            size = "L",
                            title = "Sweaters"
                        },
                        new
                        {
                            id = 5,
                            color = "yellow",
                            createdAt = "2019",
                            img = "https://images.ctfassets.net/5gvckmvm9289/3BlDoZxSSjqAvv1jBJP7TH/65f9a95484117730ace42abf64e89572/Noissue-x-Creatsy-Tote-Bag-Mockup-Bundle-_4_-2.png",
                            size = "S",
                            title = "Mens-Black-Beanie"
                        },
                        new
                        {
                            id = 6,
                            color = "white",
                            createdAt = "2021",
                            img = "https://d3o2e4jr3mxnm3.cloudfront.net/Rocket-Vintage-Chill-Cap_66374_1_lg.png",
                            size = "L",
                            title = "Plaid-Skirt"
                        },
                        new
                        {
                            id = 7,
                            color = "blue",
                            createdAt = "2012",
                            img = "https://www.pngarts.com/files/5/Black-Jacket-Transparent-Background-PNG.png",
                            size = "XL",
                            title = "Sequin-Skirt"
                        },
                        new
                        {
                            id = 8,
                            color = "gray",
                            createdAt = "2011",
                            img = "https://www.pngarts.com/files/3/Women-Jacket-PNG-High-Quality-Image.png",
                            size = "XL",
                            title = "Women-Jacket"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
